- name: Install dependencies
  sudo: yes
  yum: pkg={{item}} state=latest
  with_items:
    - git
    - tar
    - gcc
    - make
    - libffi-devel
    - zlib-devel
    - openssl-devel
    - libyaml-devel
    - readline-devel
    - ImageMagick
    - ImageMagick-devel
    - libxml2
    - libxslt
    - libxml2-devel
    - libxslt-devel
    - ntp


- name: copy localtime
  shell: cp -p /usr/share/zoneinfo/Japan /etc/localtime
  tags:
    - ntf
    - common

- name: check npt exist
  sudo: false
  stat: path=/etc/ntp.conf
  register: ntp_exist
  tags:
    - ntf
    - common

- name: put ntf.conf
  template: src=ntf.conf.j2 dest=/etc/ntp.conf
  when: ntp_exist.stat.exists == false
  tags:
    - ntf
    - common

- name: ntpdate setup
  command: ntpdate ntp.nict.jp
  when: ntp_exist.stat.exists == false
  tags:
    - ntf
    - common

- name: restart ntpd
  command: service ntpd start
  when: ntp_exist.stat.exists == false
  tags:
    - ntf
    - common

- name: chkconfig ntpd on
  command: chkconfig ntpd on
  when: ntp_exist.stat.exists == false
  tags:
    - ntf
    - common

