#!/bin/sh

echo "1" > /proc/sys/vm/overcommit_memory

echo "never" > /sys/kernel/mm/transparent_hugepage/enabled

echo "65535" > /proc/sys/net/core/somaxconn


redis-server /etc/redis.conf --protected-mode no


